FROM continuumio/miniconda3:latest

RUN conda create -n simulate_env python=3.12.1 -y
#RUN echo "source activate simulate_env" > ~/.bashrc
ENV PATH /opt/conda/envs/simulate_env/bin:$PATH

COPY ./simulate .

RUN pip install -r requirements.txt

SHELL ["conda", "run", "--name", "simulate_env", "/bin/bash", "-c"]

EXPOSE 8095

CMD ["conda", "run", "--name", "simulate_env", "python", "generate_data.py"]