FROM continuumio/miniconda3:latest

RUN conda create -n simulate_env python=3.11.5 -y

ENV PATH /opt/conda/envs/simulate_env/bin:$PATH

COPY ./simulate ./simulate

RUN pip install -r ./simulate/requirements.txt

WORKDIR /simulate

SHELL ["conda", "run", "--name", "simulate_env", "/bin/bash", "-c"]

CMD ["conda", "run", "--name", "simulate_env", "python", "generate_data2.py"]