name: CML Workflow

on:
  push:

jobs:
  train-and-report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      # Uncomment the following lines if NodeJS setup is required
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '16'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: iterative/setup-cml@v1

      - name: Install dependencies
        run: |
          pip install -r .github/workflows/requirements.txt

      - name: Train model
        run: |
          cd train
          python train.py

      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat results.txt >> report.md
          cml comment create report.md