name: CML
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v4
      - run: ldd --version
      - uses: actions/setup-python@v5
        with:
          python-version: '3.7' 

      - run: python -m pip install --upgrade pip

      - run: |
          pip install -r .github/workflows/requirements.txt
          python train/train.py  # generate plot.png
 
          # Create CML report
          cat metrics.txt >> report.md
          echo '![](./plot.png "Confusion Matrix")' >> report.md
          cml comment create report.md
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      