name: CML
on: [push]
jobs:
  train-and-report:

    permissions: write-all

    runs-on: ubuntu-latest

    container: docker://ghcr.io/iterative/cml:0-dvc2-base1

    steps:

      - name: dockercompose
        uses: hoverkraft-tech/compose-action@v1.5.1
        with:
          compose-file: "docker-compose.yaml"
          services: |
            mlflow

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - run: |
          pip install -r .github/workflows/requirements.txt
          cd train
          python train.py  # generate plot.png
          # Create CML report
          cat metrics.txt >> report.md
          cd . .

          echo '![](./plot.png "Confusion Matrix")' >> report.md
          cml comment create report.md
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}