name: format

run-name: pytests and formatting

on: [push]

jobs:

  unit-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run:
          pip install -r requirements.txt
      - run: pytest

  format-code:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT

      - name: check and format
        if: steps.git-check.outputs.modified == 'true'
        run: |
          pip install black chmod +x ./reformat.sh
          source reformat.sh
          echo ${GITHUB_REF##*/}
          git add .
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global user.name "github-actions[bot]"
          git commit -m "Auto-Reformat"
          echo "git fetch origin ${GITHUB_REF##*/}"
          git push origin ${GITHUB_REF##*/}

      
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: akashbhagran94/mlp2:latest